noun(amphibian, amphibians).
noun(block, blocks).
noun(book, books).
noun(box, boxes).
noun(boy, boys).
noun(cake, cakes).
noun(circle, circles).
noun(child, children).
noun(cookie, cookies).
noun(friend, friends).
noun(girl, girls).
noun(house, houses).
noun(kitchen, kitchens).
noun(parallelogram, parallelograms).
noun(square, squares).
noun(store, stores).
noun(table, tables).
noun(thing, things).
noun(triangle, triangles).
